language: python
python:
  - "2.6"
  - "2.7"
install: "pip install -r requirements.txt"
script: py.test
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: $HEROKU_APP_NAME
  on:
    branch: production
    condition: $TRAVIS_PYTHON_VERSION = 2.7
